### ISSUE TITLE
Falsche Gesamtanzahl der Verteilung nach Institutionen

### ISSUE THREAD

**Issue by JoschkaRichtermeier** [markusgerman/digitalcheck#14]
![2020_09_16_09_40_07_Digital_Check_Reporting_Tool](https://user-images.githubusercontent.com/69667586/93306925-c2cb1900-f800-11ea-8493-52b9162308a6.png)

In der Kreisverteilung nach den drei Umfragen (Institutionen) stimmen die Zahlen noch nicht:

IHK-KU: 46
IHK-KMU: 54
myc-KMU: 18(Vermutlich ist nur diese Zahl nicht richtig)

In Summe sind das nur 118, hier müssten wir aber auch auf 211 kommen.

**Comment by markusgerman** [comment]
fixed, danke fürs testen
